# Handover controller
handover_type: train # full or train
initial_setup: fixed
record_attempt: False

# Handover mover
handover_mover: 
    grasp_pose_mode: fixed # pc or fixed
    handover_pose_mode: sample # ik, fixed, sample or random_sample
    sample_file: workspace_analysis_22_02_2024_14_23.bag
    verbose: False
    debug: True
    analyse: True

# Grasp tester
grasp_tester: 
    debug: False
    direction: y

hand_closer: 
    closer_type: demo # threshold, pca, model or demo

    # Threshold closer
    debug: False
    collect: False
    mode: effort # effort or tactile

    # Model closer
    model_closer:
        model_path: '/models/checkpoints/sac_checkpoint_29_11_2023_16_09_5400_steps' # '/models/sac_model_29_11_2023_16_09' '/models/important_models/sac_checkpoint_23_10_2023_15_47_12900_steps'  # Without zip
        model_replay_buffer_path: '/models/checkpoints/sac_checkpoint_29_11_2023_16_09_replay_buffer_5400_steps' # '/models/sac_model_29_11_2023_16_09_replay_buffer' '/models/important_models/sac_checkpoint_23_10_2023_15_47_replay_buffer_12900_steps'  # Without pkl
        contact_modality: effort # effort or tactile

        # Structure of observation space for given model
        observation_space:                                                              
            joint_values: False                                                         
            pca: True                                                                   
            effort: True                                                                
            tactile: False                                                              
            one_hot: True   

finish_handover:
    debug: False
