# Handover controller
handover_type: full # full or train
initial_setup: fixed

# Handover mover
handover_mover: 
    side: side # top or side
    grasp_pose_mode: fixed # ik, pc or fixed
    handover_pose_mode: fixed # fixed or sample
    debug: True
    analyse: False

# Grasp tester
grasp_tester: 
    debug: False
    direction: y

hand_closer: 
    closer_type: demo # threshold, model or demo

    # Threshold closer
    debug: False
    collect: False
    mode: effort # effort or tactile

    # Model closer
    model_path: '/models/checkpoints/sac_checkpoint_29_11_2023_16_09_5400_steps' # '/models/sac_model_29_11_2023_16_09' '/models/important_models/sac_checkpoint_23_10_2023_15_47_12900_steps'  # Without zip
    model_replay_buffer_path: '/models/checkpoints/sac_checkpoint_29_11_2023_16_09_replay_buffer_5400_steps' # '/models/sac_model_29_11_2023_16_09_replay_buffer' '/models/important_models/sac_checkpoint_23_10_2023_15_47_replay_buffer_12900_steps'  # Without pkl
    model_type: "effort" # effort or tactile

finish_handover:
    debug: True
