# Handover controller
handover_type: full # full or train
initial_setup: fixed
record_attempt: False

# Handover mover
handover_mover: 
    grasp_pose_mode: fixed # pc or fixed
    handover_pose_mode: load_sample # fixed, load_sample or random_sample
    side_sample_file: workspace_analysis_side_intersection.bag 
    top_sample_file: workspace_analysis_top_intersection.bag
    debug: False
    verbose: False
    write_time: False

# Grasp tester
grasp_tester: 
    debug: False
    direction: y

hand_closer: 
    closer_type: model # threshold, model or demo

    # Threshold closer
    debug: False
    mode: effort # effort or tactile

    # Model closer
    model_closer:
        write_actions: False
        side_model_path: '/models/sac_model_29_02_2024_13_37'
        top_model_path: '/models/sac_model_19_03_2024_15_34'
        side_model_buffer: '/models/sac_model_29_02_2024_13_37_replay_buffer' 
        top_model_buffer: '/models/sac_model_19_03_2024_15_34_replay_buffer'

        # Structure of observation space for given model
        observation_space:                                                              
            joint_values: False                                                         
            pca: True
            effort: True
            tactile: False                                                              
            one_hot: True   

finish_handover:
    debug: False
