closing_model_path: '/models/checkpoints/sac_checkpoint_29_11_2023_16_09_5400_steps' # '/models/sac_model_29_11_2023_16_09' '/models/important_models/sac_checkpoint_23_10_2023_15_47_12900_steps'  # Without zip
closing_model_replay_buffer_path: '/models/checkpoints/sac_checkpoint_29_11_2023_16_09_replay_buffer_5400_steps' # '/models/sac_model_29_11_2023_16_09_replay_buffer' '/models/important_models/sac_checkpoint_23_10_2023_15_47_replay_buffer_12900_steps'  # Without pkl

model_type: "effort" # effort or tactile

debug_handover_mover: True
analyse_handover_mover: False
debug_grasp_tester: False
