cloud_filter_chain:
    - name: robot_body_filter_containment
      type: robot_body_filter/RobotBodyFilterPointCloud2
      params:
        body_model/robot_description_param: "/robot_description"
        frames/fixed: "base_footprint"
        frames/sensor: "azure_kinect_rgb_sensor"
        filter/model_pose_update_interval: 1.0
        filter/do_clipping: false
        filter/do_shadow_test: false
        bounding_box/compute: false
        body_model/inflation/scale: 2.3 #2.1 #1.7
        #body_model/inflation/contains_test/padding: 0.05
        transforms/timeout/reachable: 1.0
        transforms/timeout/unreachable: 1.0
        only_links:
            - l_shoulder_pan_link
            - l_shoulder_lift_link
            - l_upper_arm_roll_link
            - l_upper_arm_link
            - l_elbow_flex_link
            - l_forearm_roll_link
            - l_forearm_link
            - l_wrist_flex_link
            - l_wrist_roll_link
            - l_force_torque_link
            - l_gripper_palm_link
            - l_griper_l_finger_link
            - l_gripper_l_finger_tip_link
            - l_gripper_motor_accelerometer_link
            - l_gripper_r_finger_link
            - l_gripper_r_finger_tip_link
