timesteps: 10000
model_type: 'sac'
model_path: '' #/models/checkpoints/sac_checkpoint_29_11_2023_16_09_9400_steps.zip' # set either path from bimanual_handover package or empty string
checkpoint: False

# Env paramters
contact_modality: 'effort' # effort or tactile
env_check: True
record: False

observation_space:
    joint_values: False
    pca: True
    effort: True
    tactile: False
    one_hot: True

# Only used for new models
architecture:
    # List of layer sizes for actor network
    actor: 
        - 64
    # List of layer sizes for critic network
    critic:
        - 64
