timesteps: 10000
model_type: 'sac'
model_path: '' #/models/checkpoints/sac_checkpoint_29_11_2023_16_09_9400_steps.zip' # set either path from bimanual_handover package or empty string
checkpoint: False

# Env paramters
env_type: 'effort'
env_check: False
record: True

# Only used for new models
architecture:
    # List of layer sizes for actor network
    actor: 
        - 2
    # List of layer sizes for critic network
    critic:
        - 2 
